param([string]$Compiler = 'C:/Users/Owner/msys64/mingw64/bin/glslc.exe')
$ErrorActionPreference = 'Stop'
$env:PATH = (Split-Path $Compiler) + ';' + $env:PATH
foreach ($stage in @('vert', 'frag')) {
    $source = Join-Path $PSScriptRoot "gx_basic.$stage"
    & $Compiler $source -o "$source.spv"
    if ($LASTEXITCODE) { throw "Shader compilation failed: $stage" }
    $bytes = [IO.File]::ReadAllBytes("$source.spv")
    $symbol = "gx_basic_${stage}_spv"
    $lines = [Collections.Generic.List[string]]::new()
    $lines.Add("/* Generated by pc/shaders/regenerate.ps1; do not edit. */")
    $lines.Add("static const unsigned char $symbol[] __attribute__((aligned(4))) = {")
    for ($i = 0; $i -lt $bytes.Length; $i += 16) {
        $end = [Math]::Min($i + 15, $bytes.Length - 1)
        $lines.Add('    ' + (($bytes[$i..$end]) -join ',') + ',')
    }
    $lines.Add('};')
    $lines.Add("static const unsigned int ${symbol}_len = $($bytes.Length);")
    [IO.File]::WriteAllText((Join-Path $PSScriptRoot "../src/$symbol.h"), ($lines -join "`n") + "`n")
}
